// spa-sdk/examples/react-ssr/components/Banner.tsx
/*
 * Copyright 2019-2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import { Document, ImageSet } from '@bloomreach/spa-sdk';
import { BrManageContentButton, BrProps } from '@bloomreach/react-sdk';
import routes from '../routes';

const { Link } = routes;

export function Banner(props: BrProps) {
  const { document: documentRef } = props.component.getModels();
  const document = documentRef && props.page.getContent(documentRef);

  if (!document) {
    return null;
  }

  const { content, image: imageRef, link: linkRef, title } = document.getData<DocumentData>();
  const image = imageRef && props.page.getContent<ImageSet>(imageRef);
  const link = linkRef && props.page.getContent<Document>(linkRef);

  return (
    <div className={`jumbotron mb-3 ${props.page.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageContentButton content={document} />
      { title && <h1>{title}</h1> }
      { image && <img className="img-fluid" src={image.getOriginal()?.getUrl()} alt={title} /> }
      { content && <div dangerouslySetInnerHTML={{ __html: props.page.rewriteLinks(content.value) }} /> }
      { link && (
        <p className="lead">
          <Link route={link.getUrl()}>
            <a className="btn btn-primary btn-lg" role="button">Learn more</a>
          </Link>
        </p>
      ) }
    </div>
  );
}

// spa-sdk/examples/angular/src/app/banner/banner.component.ts
/*
 * Copyright 2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, Input } from '@angular/core';
import { Component as BrComponent, Document, ImageSet, Page } from '@bloomreach/spa-sdk';

@Component({
  selector: 'br-banner',
  templateUrl: './banner.component.html',
})
export class BannerComponent {
  @Input() component!: BrComponent;
  @Input() page!: Page;

  get document() {
    const { document } = this.component.getModels<DocumentModels>();

    return document && this.page.getContent<Document>(document);
  }

  get data() {
    return this.document?.getData<DocumentData>();
  }

  get image() {
    return this.data?.image && this.page.getContent<ImageSet>(this.data.image);
  }

  get link() {
    return this.data?.link && this.page.getContent<Document>(this.data.link);
  }
}

<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<div *ngIf="document" class="jumbotron mb-3" [ngClass]="{ 'has-edit-button': page.isPreview() }">
  <ng-container
    [brManageContentButton]="document"
    documentTemplateQuery="new-banner-document"
    folderTemplateQuery="new-banner-folder"
    parameter="document"
    root="banners"
    [relative]="true">
  </ng-container>
  <h1 *ngIf="data?.title">{{ data!.title }}</h1>
  <img *ngIf="image" class="img-fluid" [src]="image.getOriginal()?.getUrl()" [alt]="data?.title || ''" />
  <div *ngIf="data?.content" [innerHTML]="page.rewriteLinks(data!.content!.value)"></div>
  <p *ngIf="link" class="lead">
    <a class="btn btn-primary btn-lg"
      role="button"
      [routerLink]="link.getUrl()! | parseUrl: 'pathname'"
      [queryParams]="link.getUrl()! | parseUrl: 'searchParams'">
      Learn more
    </a>
  </p>
</div>
