// spa-sdk/examples/angular/src/app/menu/menu.component.ts
/*
 * Copyright 2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, HostBinding, Input } from '@angular/core';
import { Component as BrComponent, Menu, Page, isMenu } from '@bloomreach/spa-sdk';

@Component({
  selector: 'ul.br-menu', // tslint:disable-line: component-selector
  templateUrl: './menu.component.html',
})
export class MenuComponent {
  @Input() component!: BrComponent;
  @Input() page!: Page;

  @HostBinding('class') class = 'navbar-nav col-12';

  @HostBinding('class.has-edit-button')
  get isPreview() {
    return this.page.isPreview();
  }

  get menu() {
    const menuRef = this.component.getModels<MenuModels>()?.menu;
    const menu = menuRef && this.page.getContent<Menu>(menuRef);

    return isMenu(menu) ? menu : undefined;
  }
}

<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<ng-template [ngIf]="menu">
  <ng-container [brManageMenuButton]="menu"></ng-container>

  <li *ngFor="let item of menu.siteMenuItems" key={index} class="nav-item" [ngClass]="{ active: item.selected }">
    <span *ngIf="!item._links.site"
      class="nav-link text-capitalize disabled">
      {{ item.name }}
    </span>

    <a *ngIf="item._links.site | isExternalLink"
      class="nav-link text-capitalize"
      [href]="item._links.site.href">
      {{ item.name }}
    </a>

    <a *ngIf="item._links.site | isInternalLink"
      class="nav-link text-capitalize"
      [routerLink]="page.getUrl(item._links.site) | parseUrl: 'pathname'"
      [queryParams]="page.getUrl(item._links.site) | parseUrl: 'searchParams'">
      {{ item.name }}
    </a>
  </li>
</ng-template>

// spa-sdk/examples/next/components/Menu.tsx
/*
 * Copyright 2019-2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import Link from 'next/link';
import { MenuItem, Menu as BrMenu, TYPE_LINK_EXTERNAL, isMenu } from '@bloomreach/spa-sdk';
import { BrComponentContext, BrManageMenuButton, BrPageContext } from '@bloomreach/react-sdk';

interface MenuLinkProps {
  item: MenuItem;
}

function MenuLink({ item }: MenuLinkProps) {
  const url = item.getUrl();

  if (!url) {
    return <span className="nav-link text-capitalize disabled">{item.getName()}</span>;
  }

  if (item.getLink()?.type === TYPE_LINK_EXTERNAL) {
    return <a className="nav-link text-capitalize" href={url}>{item.getName()}</a>;
  }

  return (
    <Link href={url}>
      <a className="nav-link text-capitalize">{item.getName()}</a>
    </Link>
  );
}

export function Menu() {
  const component = React.useContext(BrComponentContext);
  const page = React.useContext(BrPageContext);
  const menuRef = component?.getModels<MenuModels>()?.menu;
  const menu = menuRef && page?.getContent<BrMenu>(menuRef);

  if (!isMenu(menu)) {
    return null;
  }

  return (
    <ul className={`navbar-nav col-12 ${page!.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageMenuButton menu={menu} />
      { menu.getItems().map((item, index) => (
        <li key={index} className={`nav-item ${item.isSelected() ? 'active' : ''}`}>
          <MenuLink item={item} />
        </li>
      )) }
    </ul>
  );
}
