// spa-sdk/packages/react-sdk/src/component/BrNodeContainerItem.tsx
/*
 * Copyright 2019 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import { ContainerItem } from '@bloomreach/spa-sdk';
import { BrContainerItemUndefined } from '../cms';
import { BrNodeComponent } from './BrNodeComponent';
import { BrProps } from './BrProps';

export class BrNodeContainerItem extends BrNodeComponent<ContainerItem> {
  constructor(props: BrProps<ContainerItem>) {
    super(props);

    this.onUpdate = this.onUpdate.bind(this);
  }

  componentDidMount() {
    this.props.component.on('update', this.onUpdate);
  }

  componentWillUnmount() {
    this.props.component.off('update', this.onUpdate);
  }

  protected getMapping() {
    return this.props.component.getType();
  }

  protected fallback() {
    return <BrContainerItemUndefined {...this.props} />;
  }

  protected onUpdate() {
    this.forceUpdate(() => this.props.page.sync());
  }
}

// spa-sdk/packages/vue-sdk/src/BrNodeContainerItem.vue
<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<template>
  <component :is="mapping[component.getType()]" :component="component" :page="page" />
</template>

<script lang="ts">
import { ContainerItem, Page } from '@bloomreach/spa-sdk';
import { Component, InjectReactive, Inject, Vue, Watch } from 'vue-property-decorator';

@Component({
  computed: {
    component(this: BrNodeContainerItem) {
      return this.component$();
    },
  },
})
export default class BrNodeContainerItem extends Vue {
  @Inject() private component$!: () => ContainerItem;

  private component!: ContainerItem;

  @InjectReactive() private mapping!: Record<string, Vue.Component>;

  @InjectReactive() private page!: Page;

  private unsubscribe?: Function;

  destroyed() {
    this.unsubscribe?.();
  }

  @Watch('component', { immediate: true })
  private subscribe() {
    this.unsubscribe?.();
    this.unsubscribe = this.component.on('update', this.onUpdate.bind(this));
  }

  private onUpdate() {
    this.$forceUpdate();
    this.page.sync();
  }
}
</script>
