// spa-sdk/packages/ng-sdk/src/lib/br-page/br-page.component.ts
/*
 * Copyright 2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { AfterViewChecked, Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { destroy, initialize, isPage, Configuration, Page, PageModel } from '@bloomreach/spa-sdk';
import { from } from 'rxjs';
import { map } from 'rxjs/operators';

/**
 * The brXM page.
 */
@Component({
  selector: 'br-page',
  templateUrl: './br-page.component.html'
})
export class BrPageComponent implements AfterViewChecked, OnChanges, OnDestroy {
  /**
   * The configuration of the SPA SDK.
   * @see https://www.npmjs.com/package/@bloomreach/spa-sdk#configuration
   */
  @Input() configuration!: Omit<Configuration, 'httpClient'>;

  /**
   * The pre-initialized page instance or prefetched page model.
   * Mostly this property should be used to transfer state from the server-side to the client-side.
   */
  @Input() page?: Page | PageModel;

  state?: Page = undefined;

  constructor(private httpClient: HttpClient) {
    this.request = this.request.bind(this);
  }

  ngAfterViewChecked() {
    this.state?.sync();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.configuration?.currentValue !== changes.configuration?.previousValue
      || changes.page?.currentValue !== changes.page?.previousValue
    ) {
      this.destroy();
      this.initialize(changes.page?.currentValue === changes.page?.previousValue);
    }
  }

  ngOnDestroy() {
    this.destroy();
  }

  private destroy() {
    if (!this.state) {
      return;
    }

    destroy(this.state);
  }

  private initialize(force: boolean) {
    const page = force ? undefined : this.page;

    if (isPage(page)) {
      this.state = page;

      return;
    }

    from(initialize({ httpClient: this.request, ...this.configuration } as Configuration, page))
      .subscribe(state => { this.state = state; });
  }

  private request(...[{ data: body, headers, method, url }]: Parameters<Configuration['httpClient']>) {
    return this.httpClient.request<PageModel>(
      method,
      url,
      {
        body,
        headers: headers as Record<string, string | string[]>,
        responseType: 'json'
      },
    )
    .pipe(map(data => ({data})))
    .toPromise();
  }
}

<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<br-component *ngIf="state"></br-component>

// spa-sdk/packages/vue-sdk/src/BrPage.vue
<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<template>
  <br-node-component v-if="state" :component="root">
    <slot :component="root" :page="state" />
  </br-node-component>
</template>

<script lang="ts">
import { Configuration, PageModel, Page, initialize, isPage, destroy } from '@bloomreach/spa-sdk';
import { Component, Prop, ProvideReactive, Vue, Watch } from 'vue-property-decorator';
import BrNodeComponent from './BrNodeComponent.vue';

/**
 * The brXM page.
 */
@Component({
  components: { BrNodeComponent },
  computed: {
    root(this: BrPage) {
      return this.state?.getComponent();
    },
  },
  data: () => ({ state: undefined }),
  name: 'br-page',
})
export default class BrPage extends Vue {
  /**
   * The configuration of the SPA SDK.
   * @see https://www.npmjs.com/package/@bloomreach/spa-sdk#configuration
   */
  @Prop() configuration!: Configuration;

  /**
   * The brXM and Vue.js components mapping.
   */
  @Prop() @ProvideReactive() mapping!: Record<string, Vue.Component>;

  /**
   * The pre-initialized page instance or prefetched page model.
   * Mostly this property should be used to transfer state from the server-side to the client-side.
   */
  @Prop() page?: Page | PageModel;

  /**
   * The current state of the page component.
   */
  @ProvideReactive('page') state?: Page;

  private loading?: Promise<void>;

  async serverPrefetch() {
    await this.loading;
  }

  destroyed() {
    this.destroy();
  }

  mounted() {
    this.state?.sync();
  }

  updated() {
    this.state?.sync();
  }

  @Watch('configuration', { immediate: true, deep: true })
  private async update(current: Configuration, previous?: Configuration) {
    this.destroy();
    this.loading = this.initialize(previous ? undefined : this.page);
    await this.loading;
    delete this.loading;
  }

  private async initialize(page?: Page | PageModel) {
    if (isPage(page)) {
      this.state = page;

      return;
    }

    this.state = await initialize(this.configuration, page);
  }

  private destroy() {
    if (this.state) {
      destroy(this.state);
    }
  }
}
</script>
