// spa-sdk/examples/react-csr/src/components/Menu.tsx
/*
 * Copyright 2019 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import { BrComponentContext, BrManageMenuButton, BrPageContext } from '@bloomreach/react-sdk';

export function Menu() {
  const component = React.useContext(BrComponentContext);
  const page = React.useContext(BrPageContext);
  if (!component || !page) {
    return null;
  }

  const { menu } = component.getModels<MenuModels>();

  return (
    <ul className={`navbar-nav col-12 ${page.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageMenuButton menu={menu} />
      { menu.siteMenuItems.map((item, index) => (
        <li key={index} className={`nav-item ${item.selected ? 'active' : ''}`}>
          <a className="nav-link text-capitalize" href={page.getUrl(item._links.site!)}>{item.name}</a>
        </li>
      )) }
    </ul>
  );
}

// spa-sdk/examples/angular/src/app/menu/menu.component.ts
/*
 * Copyright 2020 Hippo B.V. (http://www.onehippo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, HostBinding, Input } from '@angular/core';
import { Component as BrComponent, Page } from '@bloomreach/spa-sdk';

@Component({
  selector: 'ul.br-menu', // tslint:disable-line: component-selector
  templateUrl: './menu.component.html',
})
export class MenuComponent {
  @Input() component!: BrComponent;
  @Input() page!: Page;

  @HostBinding('class') class = 'navbar-nav col-12';

  @HostBinding('class.has-edit-button')
  get isPreview() {
    return this.page.isPreview();
  }

  get menu() {
    return this.component.getModels<MenuModels>()?.menu;
  }
}

<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<ng-template [ngIf]="menu">
  <ng-container [brManageMenuButton]="menu"></ng-container>

  <li *ngFor="let item of menu.siteMenuItems" key={index} class="nav-item" [ngClass]="{ active: item.selected }">
    <span *ngIf="!item._links.site"
      class="nav-link text-capitalize disabled">
      {{ item.name }}
    </span>

    <a *ngIf="item._links.site | isExternalLink"
      class="nav-link text-capitalize"
      [href]="item._links.site.href">
      {{ item.name }}
    </a>

    <a *ngIf="item._links.site | isInternalLink"
      class="nav-link text-capitalize"
      [routerLink]="page.getUrl(item._links.site) | parseUrl: 'pathname'"
      [queryParams]="page.getUrl(item._links.site) | parseUrl: 'searchParams'">
      {{ item.name }}
    </a>
  </li>
</ng-template>
